export const colorArray = [
    {
        name: 'Default',
        color: {
            bg: '#134e4a',
            bgComponent: '#115e59',
            foreground: '#042f2e',
            caret: '#fb923c',
            text: '#0d9488',
            textActive: '#99f6e4',
            error: '#ff585d',
            comment: '#75715E',
        },
    },
    {
        name: 'Monokai',
        color: {
            bg: '#272822',
            bgComponent: '#1f201b',
            foreground: '#F8F8F2',
            caret: '#66d9ef',
            text: '#e6db74',
            textActive: '#A6E22E',
            error: '#F92672',
            comment: '#75715E',
        },
    },
    {
        name: 'Solarized Dark',
        color: {
            bg: '#083642',
            bgComponent: '#032b36',
            foreground: '#fdf6e3',
            caret: '#268bd2',
            text: '#657b83',
            textActive: '#38d8cc',
            error: '#dc322e',
            comment: '#b58901',
        },
    },
    {
        name: 'Solarized Light',
        color: {
            bg: '#fdf6e3',
            bgComponent: '#eee8d5',
            foreground: '#083642',
            caret: '#cb4b17',
            text: '#032b36',
            textActive: '#2aa198',
            error: '#d33682',
            comment: '#93a1a1',
        },
    },
    {
        name: 'Dracula',
        color: {
            bg: '#282A36',
            bgComponent: '#44475a',
            foreground: '#F8F8F2',
            caret: '#ffb86c',
            text: '#6272A4',
            textActive: '#50fa7b',
            error: '#ff5555',
            comment: '#6272A4',
        },
    },
    {
        name: 'Gruvbox dark',
        color: {
            bg: '#514945',
            bgComponent: '#202020',
            foreground: '#d4be98',
            caret: '#d8a657',
            text: '#a9b665',
            textActive: '#abecdd',
            error: '#ea6962',
            comment: '#89b482',
        },
    },
    {
        name: 'Gruvbox light',
        color: {
            bg: '#d5c4a1',
            bgComponent: '#f9f5d7',
            foreground: '#654735',
            caret: '#b47108',
            text: '#45707a',
            textActive: '#8ea700',
            error: '#c1494a',
            comment: '#89b482',
        },
    },
    {
        name: 'One Dark Pro',
        color: {
            bg: '#282c34',
            bgComponent: '#4b5263',
            foreground: '#abb2bf',
            caret: '#61afef',
            text: '#98c379',
            textActive: '#e5c07b',
            error: '#e06c75',
            comment: '#5c6370',
        },
    },
    {
        name: 'Tomorrow Night',
        color: {
            bg: '#1d1f21',
            bgComponent: '#373b41',
            foreground: '#c5c8c6',
            caret: '#de935f',
            text: '#8abeb7',
            textActive: '#b5bd68',
            error: '#cc6666',
            comment: '#969896',
        },
    },
    {
        name: 'Tomorrow Night Blue',
        color: {
            bg: '#002451',
            bgComponent: '#003f8e',
            foreground: '#ffffff',
            caret: '#ffc58f',
            text: '#99ffff',
            textActive: '#d1f1a9',
            error: '#ff9da4',
            comment: '#7285b7',
        },
    },
    {
        name: 'Tomorrow Night Bright',
        color: {
            bg: '#000000',
            bgComponent: '#424242',
            foreground: '#eaeaea',
            caret: '#e7c547',
            text: '#c397d8',
            textActive: '#70c0b1',
            error: '#d54e53',
            comment: '#969896',
        },
    },
    {
        name: 'Material Oceanic',
        color: {
            bg: '#263238',
            bgComponent: '#32424A',
            foreground: '#B0BEC5',
            caret: '#009688',
            text: '#c792ea',
            textActive: '#c3e88d',
            error: '#ff5370',
            comment: '#546e7a',
        },
    },
    {
        name: 'Material Darker',
        color: {
            bg: '#212121',
            bgComponent: '#292929',
            foreground: '#B0BEC5',
            caret: '#89ddff',
            text: '#80cbc4',
            textActive: '#c3e88d',
            error: '#ff5370',
            comment: '#616161',
        },
    },
    {
        name: 'Material Lighter',
        color: {
            bg: '#FAFAFA',
            bgComponent: '#dedede',
            foreground: '#546E7A',
            caret: '#009688',
            text: '#272727',
            textActive: '#91b859',
            error: '#e53935',
            comment: '#AABFC9',
        },
    },
    {
        name: 'Material Palenight',
        color: {
            bg: '#292D3E',
            bgComponent: '#34324a',
            foreground: '#A6ACCD',
            caret: '#ffcb6b',
            text: '#717CB4',
            textActive: '#89ddff',
            error: '#ff5370',
            comment: '#676E95',
        },
    },
    {
        name: 'Material Forest',
        color: {
            bg: '#002626',
            bgComponent: '#002E2E',
            foreground: '#B2C2B0',
            caret: '#FFCC80',
            text: '#49694D',
            textActive: '#c3e88d',
            error: '#ff5370',
            comment: '#005454',
        },
    },
    {
        name: 'Material Sky Blue',
        color: {
            bg: '#F5F5F5',
            bgComponent: '#e7f2f3',
            foreground: '#005761',
            caret: '#f76d47',
            text: '#01579B',
            textActive: '#00c6e0',
            error: '#e53935',
            comment: '#272727',
        },
    },
    {
        name: 'Material Sandy Beach',
        color: {
            bg: '#FFF8ED',
            bgComponent: '#f6edda',
            foreground: '#546E7A',
            caret: '#f76d47',
            text: '#888477',
            textActive: '#6ec8f4',
            error: '#e53935',
            comment: '#272727',
        },
    },
    {
        name: 'Nord',
        color: {
            bg: '#2e3440',
            bgComponent: '#343b49',
            foreground: '#88c0d0',
            caret: '#e5e9f0',
            text: '#82a0c1',
            textActive: '#ebcb8b',
            error: '#bf616a',
            comment: '#75715E',
        },
    },
    {
        name: 'Cobalt2',
        color: {
            bg: '#193549',
            bgComponent: '#14232d',
            foreground: '#aaaaaa',
            caret: '#ffc600',
            text: '#a5ff90',
            textActive: '#e1efff',
            error: '#ff5630',
            comment: '#0088ff',
        },
    },
    {
        name: 'Ayu Light',
        color: {
            bg: '#f8f9fa',
            bgComponent: '#fcfcfc',
            foreground: '#8a9199',
            caret: '#ffaa34',
            text: '#e6ba7e',
            textActive: '#6cbf43',
            error: '#e65051',
            comment: '#787B80',
        },
    },
    {
        name: 'Ayu Mirage',
        color: {
            bg: '#1f2530',
            bgComponent: '#242a36',
            foreground: '#707a8c',
            caret: '#ffcc66',
            text: '#ffdfb3',
            textActive: '#87d96c',
            error: '#ff6566',
            comment: '#B8CFE6',
        },
    },
    {
        name: 'Ayu Dark',
        color: {
            bg: '#0b0e14',
            bgComponent: '#141621',
            foreground: '#565b66',
            caret: '#e6b450',
            text: '#e6b673',
            textActive: '#7fd962',
            error: '#d95757',
            comment: '#ACB6BF',
        },
    },
    {
        name: 'Night Owl',
        color: {
            bg: '#011627',
            bgComponent: '#0b2942',
            foreground: '#D6DEEB',
            caret: '#80A4C2',
            text: '#5f7e97',
            textActive: '#7fdbca',
            error: '#ef5350',
            comment: '#637777',
        },
    },
    {
        name: 'Light Owl',
        color: {
            bg: '#F0F0F0',
            bgComponent: '#FBFBFB',
            foreground: '#403f53',
            caret: '#c96765',
            text: '#90A7B2',
            textActive: '#1daa9f',
            error: '#de3d3b',
            comment: '#989fb1',
        },
    },
    {
        name: 'Tokyo Night',
        color: {
            bg: '#24283b',
            bgComponent: '#1a1c27',
            foreground: '#7aa2f7',
            caret: '#a9b1d6',
            text: '#af8c5c',
            textActive: '#95c267',
            error: '#f7768e',
            comment: '#9da5c9',
        },
    },
    {
        name: "SynthWave '84",
        color: {
            bg: '#2a2139',
            bgComponent: '#241b2f',
            foreground: '#ffffff',
            caret: '#f92aad',
            text: '#848bbd',
            textActive: '#36f9f6',
            error: '#fe4450',
            comment: '#848bbd',
        },
    },
];
